name: Run Tests and Notify on Slack

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 17 * * *'  # Runs every day at 5:00 PM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: self-hosted  # Using your self-hosted runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache .NET SDK
        uses: actions/cache@v3
        with:
          path: ~/.dotnet
          key: ${{ runner.os }}-dotnet-${{ hashFiles('**/global.json') }}
          restore-keys: |
            ${{ runner.os }}-dotnet-

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the solution
        run: dotnet build --configuration Release

      - name: Run Tests
        run: dotnet test --configuration Release --logger "trx;LogFileName=test_results.trx"
        continue-on-error: true

      - name: Send Slack Notification on Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: "🚨 *Test Failure Alert!* Your tests have failed. Check GitHub Actions for details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Send Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: "✅ *Test Success!* All tests passed successfully. 🎉"
