name: Run Tests and Notify on Slack

on:
  schedule:
    - cron: '0 17 * * *'  # Runs every day at 5:00 PM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: self-hosted  # Using your self-hosted runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          dotnet restore  # Restores the dependencies and tools of a project

      - name: Run Tests
        id: test_step
        run: |
          dotnet test  # Runs the tests using the test runner specified in the project

      - name: Send Slack Notification on Failure
        if: failure()  # Only runs if the test fails
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"🚨 *Test Failure Alert!* Your tests have failed. Check GitHub Actions for details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}' "$SLACK_WEBHOOK_URL"

      - name: Send Slack Notification on Success
        if: success()  # Only runs if the test succeeds
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"✅ *Test Success!* All tests passed successfully. 🎉"}' "$SLACK_WEBHOOK_URL"
